### PR TITLE
Update version to 3.16.5

### PR DESCRIPTION
**Pull request by kszucs**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kszucs** [comment]
@conda-forge-admin, please rerender

**Comment by kszucs** [comment]
@conda-forge-admin, please lint

**Comment by kszucs** [comment]
@conda-forge-admin, please rerender

**Comment by kszucs** [comment]
I'm not sure what's going on, the linter was complaining in an unusual way and the linux build seemingly [expects that it runs on macOS](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=130302&view=logs&j=1bf226d3-0e2f-52d8-fa93-7d9e633347b3&t=ec8d466d-e3b4-5115-4f06-222398f91e6c&l=5954)?

**Comment by xhochy** [comment]
@kszucs I had a similar issue in https://github.com/conda-forge/nodejs-feedstock/pull/121/files#diff-44a73bcc045c193c3bd45da87994b03b where I needed to delete a file. This was ok as there I didn't need that one on Linux.

**Comment by jakirkham** [comment]
We were looking at going to 3.17.0 in PR ( https://github.com/conda-forge/cmake-feedstock/pull/115 ). Would we still want this patch release in that case or would it make sense to concentrate our efforts on 3.17.0?

cc @trxcllnt

**Comment by jakirkham** [comment]
Thanks @kszucs! 😄

**Comment by kszucs** [comment]
@jakirkham You're welcome :)

**Pull request merged**
