### PR TITLE
Use run exports

### PR DESCRIPTION
**Pull request by jschueller**
Closes #180

### CODE REVIEW

**Comment by zklaus** [comment]
@jschueller, could I ask you to hold off on this one until #193 is in? This way, there will be one less build in need of a repodata patch.

**Comment by jschueller** [comment]
ah too late

**Comment by zklaus** [comment]
That's alright, no problem :)

**Comment by isuruf** [comment]
@jschueller, I would appreciate it if you don't use my commits like this without giving credit in the future.

**Comment by jschueller** [comment]
sorry, I couldnt cherry-pick because of the conflicts

**Comment by isuruf** [comment]
In that case, you can add me as the author by adding `--author` to `git commit`, or let me know and I can do it for you.

**Pull request merged**
