### PR TITLE
Disable ccmake

### PR DESCRIPTION
**Pull request by jschueller**
Fixes https://github.com/conda-forge/cmake-feedstock/issues/20

### CODE REVIEW

**Comment by isuruf** [comment]
ccmake works fine for me

**Comment by jschueller** [comment]
We dont provide all the libs (curses, form etc) so it's not garanteed to work, so better disable it.

**Comment by isuruf** [comment]
Installing cmake in a separate env pulls in ncurses (libncurses and libform) and it works.

**Comment by jschueller** [comment]
ok

**Comment by jakirkham** [comment]
Building things like `cmake` will get a lot better once we move to `conda-build` 3. ( https://github.com/conda/conda-build/pull/2579 )

**Pull request closed without merging**
