### PR TITLE
Update to 3.7.1

### LINKED ISSUE #24: CMake 3.7.1 is released
https://cmake.org/download/

P.S. I just wanted to let you know.

### PR DESCRIPTION
**Pull request by frol**
Closes #24.

### CODE REVIEW

**Comment by frol** [comment]
@jakirkham It seems to be ready to merge. AppVeyor and CircleCI are green and [Travis OS X infrastructure is under a heavy load](https://www.traviscistatus.com/incidents/nq0sf0srvx8s).

NOTE: Since 3.7.0 release, libuv dependency was opted to be a system dependency by default. There was no `libuv` package in Anaconda, so I fell back to the old behavior building libuv together with CMake (`CMAKE_USE_SYSTEM_LIBRARY_LIBUV=OFF`). Thus, I went ahead and created an initial version of `libuv` recipe: https://github.com/conda-forge/staged-recipes/pull/2031

**Comment by jakirkham** [comment]
Yep, smart. Thanks for doing that @frol .

Currently our Windows builds of `cmake` are repackaged binaries, which we'd be eager to get away from. That being said, if that is your motivation for a Windows build of `libuv`, please don't feel obligated.

**Comment by frol** [comment]
@jakirkham I haven't worked on Windows for over than 10 years now, so I don't really care about it myself, but it is still nice to support all the platforms if the project supports them... In fact, I just failed to use the proper flag to the CMake `./bootstrap` script, this is why I went the hard way of creating libuv recipe in the first place. Yet, since it is working fine without the external `libuv`, I won't put more effort into the recipe, so I decided to share it as it is.

**Comment by jakirkham** [comment]
As we already have gone to the effort to separate dependency out of `cmake`, I really think we should be doing the same thing with `libuv` and not using a preincluded copy. TBH the great thing about a package manager is the ability to manage libraries that properly separate concerns. Falling back to bundling them like this should be a last resort.

**Comment by frol** [comment]
@jakirkham It used to work like this, so I don't think it is a road blocker for 3.7.1 release. We may address it later once `libuv` recipe is ready. Let's merge this now.

**Comment by isuruf** [comment]
Needs a rerender

**Comment by frol** [comment]
Updated. Added `libuv` dependency instead of `-DCMAKE_USE_SYSTEM_LIBRARY_LIBUV=OFF`, and rerendered.

**Comment by frol** [comment]
Windows build failed with

```
%CMD_IN_ENV% conda build recipe --quiet
1 was unexpected at this time.
```

Any thoughts?

**Comment by isuruf** [comment]
That's strange. I've no idea.

**Comment by frol** [comment]
@jakirkham AppVeyor failed unexpectantly after the rerender. Could you, please, take a look at the error as my mind is blank? Second, CircleCI never started after the rerendering... Why? :(

**Comment by scopatz** [comment]
Circle is having general problems right now.

**Comment by jakirkham** [comment]
Please upgrade to 1.6.1 and re-render again.

**Comment by frol** [comment]
All green!

**Comment by scopatz** [comment]
this didn't run on circle

**Comment by frol** [comment]
@scopatz Yep, but I cannot fix it, can I?

**Comment by isuruf** [comment]
Here's a build in my fork, https://circleci.com/gh/isuruf/cmake-feedstock/3
This branch is up-to-date with master.

**Comment by frol** [comment]
@isuruf Thanks. It passes! Should somebody merge it? (I have no permissions to do that.)

**Comment by jakirkham** [comment]
FYI here's the info on the CircleCI issue.

xref: https://github.com/conda-forge/status/issues/30

**Comment by jakirkham** [comment]
Any other comments?

**Comment by jakirkham** [comment]
Oh @frol could you please double check that the line endings in the recipe (particularly `bld.bat`) are correct?

**Comment by frol** [comment]
@jakirkham I haven't touched `bld.bat`, but it has LF instead of CRLF. `build.sh` and `meta.yaml` are both using LF. I believe, the `.gitattributes` config takes care of the LF/CRLF on clone and commit, at least, I couldn't commit the force change LF to CRLF for `bld.bat`.

**Comment by jakirkham** [comment]
Normally it does, but I ran into an odd case the other night where it started rewriting the file locally instead. It may have been an old copy of `git` that created the repo thus causing the issue.

In any event, am not seeing the issue with this feedstock or your PR either. So looks good. Thanks for checking.

**Comment by frol** [comment]
Merge?

**Comment by scopatz** [comment]
This isn't running on Circle for some reason, and so it might not work on Linux.

**Comment by scopatz** [comment]
Code-wise it LGTM, though!

**Comment by isuruf** [comment]
@scopatz see https://github.com/conda-forge/cmake-feedstock/pull/25#issuecomment-266021191

**Comment by scopatz** [comment]
Ok this builds on linux docker for me. Thanks!

**Pull request merged**
