### PR TITLE
v3.6.2 bump

### PR DESCRIPTION
**Pull request by scopatz**
A new micro version of CMake is out that I am hoping has some needed bug fixes in it.

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks @scopatz.

**Comment by jakirkham** [comment]
What bugs were you encountering with CMake?

**Comment by jakirkham** [comment]
FYI Changelog:

```
Changes in 3.6.2 since 3.6.1:

Ben Boeckel (3):
      Intel-C: declare support for gnu11
      Intel-C: support gnu89 and gnu99 extension flags
      Intel-C: standard flags are also supported in 12.0

Brad King (11):
      Add script to update curl from upstream
      curl: Update script to get curl 7.50.1
      curl: Remove CMake-specific README
      VS: Fix VS 2015 .vcxproj debug setting for Windows7.1SDK toolset
      GetPrerequisites: Fix regression in gp_resolved_file_type
      Fortran: Fix .mod file comparison for Intel 16 format
      VS: Fix VS 2015 .vcxproj debug setting for v80 toolset
      FindHDF5: Fix regression in providing HDF5_IS_PARALLEL
      FindHDF5: Fix regression in finding hdf5hl_fortran
      curl: Backport certificate reuse fix from 7.50.2
      CMake 3.6.2

Chuck Atkins (2):
      FindHDF5: Make sure compile definition vars keep the -D flag
      CrayLinuxEnvironment: Add alternative methods to get version info

Curl Upstream (2):
      curl 2015-08-11 (1a7f66a3)
      curl 2016-08-03 (f2cb3a01)

Fujii Hironori (1):
      VS: Fix out-of-bounds write on empty Nsight Tegra version

Konstantin Sinitsyn (1):
      FindProtobuf: Restore support for PROTOBUF_IMPORT_DIRS
```

**Comment by jakirkham** [comment]
Also would be happy to have you as a maintainer. 😄

**Comment by scopatz** [comment]
Thanks @jakirkham! I saw the changelog, but it wasn't clear from that if it will fix things.  I am tyring to get a pyne recipe up, and I was getting one of two weird errors:

1. If I used an old version of FindHDF5.cmake and specified FC=gfortran, HDF5_LIBRARIES would fail.
2. If I use the v3.6 version of FindHDF5.cmake, everything is found correctly,  but compiling fails because it the compile flags have a raw `BOOST_MATH_DISABLE_FLOAT128`... that is, the `-D` in `-DBOOST_MATH_DISABLE_FLOAT128` seems to be removed from the CXXFLAGS. PyNE and CMake itself don't set this, so I am guessing it it comes from an error in CMake parsing some of the pkg-config files.

**Comment by scopatz** [comment]
> Also would be happy to have you as a maintainer. :smile:

Sure thing :)

**Comment by jakirkham** [comment]
So the Boost flag is set by `toolchain` on Linux. Though the stripping of`-D` is unusual.

We recently added Fortran support to HDF5. So these fixes may be on point for the issues described.

**Comment by jakirkham** [comment]
>> Also would be happy to have you as a maintainer. :smile:

> Sure thing :)

Please see PR ( https://github.com/conda-forge/cmake-feedstock/pull/17 ).

**Comment by scopatz** [comment]
> So the Boost flag is set by the toolchain on Linux. Though the stripping of-D is unusual.

> We recently added Fortran support to HDF5. So these fixes may be on point for the issues described.

Sure.  But the reason I think this is a CMake issue is that if I grep through the whole anaconda dir, all instance of `BOOST_MATH_DISABLE_FLOAT128` are preceded by the correct `-D`.  I can't find a single place where it doesn't.  This seems like it would be a CMake issue.

**Comment by scopatz** [comment]
For what it is worth, the bump to v3.6.2 did seem to fix the `-D` issue.

**Pull request merged**
