### PR TITLE
Add build of ccmake also on Windows

### PR DESCRIPTION
**Pull request by traversaro**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
Actually the feature is only available from CMake 3.23, we need to wait for that release.

**Comment by traversaro** [comment]
@conda-forge/core The PR is ready for review.

**Comment by isuruf** [comment]
@traversaro, you should ping @conda-forge/cmake, not core.

**Comment by jakirkham** [comment]
Thanks Silvio! 😄

**Comment by traversaro** [comment]
> @traversaro, you should ping @conda-forge/cmake, not core.

Probably I just autocompleted `@conda-force/c` , sorry for the noise!

**Pull request merged**
