### PR TITLE
Use run_exports

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks Isuru! 🙏

**Comment by jakirkham** [comment]
Weird the builds got all the way to the end, but failed. Not clear why. Trying to restart the failed builds

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by JanuszL** [comment]
Will that change fix the recent problem introduced by the rhash lib so name change:
```
cmake: error while loading shared libraries: librhash.so.0: cannot open shared object file: No such file or directory
```?

**Comment by jakirkham** [comment]
> Will that change fix the recent problem introduced by the rhash lib so name change:
> 
> ```
> cmake: error while loading shared libraries: librhash.so.0: cannot open shared object file: No such file or directory
> ```?
> ```

^ @jschueller does this sound familiar?

**Comment by jschueller** [comment]
no

**Pull request closed without merging**
