### PR TITLE
add cmake-ar

### PR DESCRIPTION
**Pull request by hmaarrfk**
Without this, it uses system `/usr/bin/ar`. You can't really uninstall binutils from centos. In my docker container, I just remove those files with `rm` to ensure I don't use them.

See builds 2 and 3 from
https://app.shippable.com/github/Archiconda/cmake-feedstock/dashboard/history

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
xref https://github.com/conda-forge/toolchain-feedstock/pull/53/files

**Comment by jakirkham** [comment]
Isn't there one provided with the compilers?

cc @mingwandroid

**Comment by hmaarrfk** [comment]
There is, but without this flag it uses `/usr/bin/ar`

**Comment by jakirkham** [comment]
Are there other things like this we should be setting (e.g. `nm`)?

**Comment by mingwandroid** [comment]
Hi @hmaarrfk, I'm not entirely sure what you have in place at present but I think you'd be better off building compilers here or at least fake compiler activation packages that set all these variables (they could even run yum etc to install system tools if detected as not being present).

This would keep things working in a more uniform way, from the perspective of the recipes.

I built an arm5 miniconda this way ages ago and in fact our current Linux compilers grew out of that work!

To build a miniconda from scratch (touchy you likely don't want to it need to do that now) you have two choices, build everything on a 'system' qemu setup where both host and build are aarch64 or else use a 'user' qemu with binfmt_misc. When using the latter build can be either aarch64 or amd64, but to bootstrap you'd probably need build to be amd64, otherwise you need to use the system python to run conda and conda-build until you have got as far as building python.

**Comment by hmaarrfk** [comment]
@mingwandroid with alot of help from jjhelmus, I basically have python 3.7, python 2.7 built, and python 3.6 is building now. I just invited you to join, mostly giving you the right to push jobs to shippable if you like.

I currently built python 3.6 and 3.7 without optimization. Not sure how the 96 Core CPUs they have affects things. You are free to play with them if you want to kill some time

Most of the work is done in this repo
https://github.com/Archiconda/build-tools
and a fork of conda-smithy I have enabled.

**Comment by jakirkham** [comment]
Is this PR still needed?

**Comment by hmaarrfk** [comment]
No, this has been taken care of in `CMAKE_ARGS`.

Man i can't believe this is 2 years ago now....

**Comment by hmaarrfk** [comment]
Wait 3.

**Pull request closed without merging**
