### PR TITLE
Backport --debug-find to 3.16.2 and update to that version

### PR DESCRIPTION
**Pull request by mingwandroid**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by scopatz** [comment]
probably need to bump the build number now too

**Comment by mingwandroid** [comment]
I reset it to 0?

**Comment by jakirkham** [comment]
There was already a PR merged for 3.16.2 though.

**Comment by mingwandroid** [comment]
Ah sorry. Should we bump the build? This new feature is really helpful..

**Comment by jakirkham** [comment]
Yeah we should. The package didn't ship. Submitted PR ( https://github.com/conda-forge/cmake-feedstock/pull/107 ) to bump the build number 🙂

**Pull request merged**
